In [1]:
import pandas as pd

In [2]:
s = pd.Series(list('asdadeadesdasesda'))
s

0     a
1     s
2     d
3     a
4     d
5     e
6     a
7     d
8     e
9     s
10    d
11    a
12    s
13    e
14    s
15    d
16    a
dtype: object

In [3]:
#Verifica os valores não repetidos na Series
s.unique()

array(['a', 's', 'd', 'e'], dtype=object)

In [4]:
#conta quantos valores possui de cada
s.value_counts()

a    5
d    5
s    4
e    3
dtype: int64

In [5]:
dados = pd.read_csv('dados/aluguel.csv', sep=';')

In [6]:
dados.Tipo.unique()

array(['Apartamento', 'Casa', 'Casa de Condomínio', 'Casa de Vila',
       'Quitinete'], dtype=object)

In [7]:
dados['Tipo'].value_counts()

Apartamento           16923
Casa de Condomínio      964
Casa                    898
Quitinete               813
Casa de Vila            233
Name: Tipo, dtype: int64

In [8]:
m1 = 'CCcCCccCCCccCcCccCcCcCCCcCCcccCCcCcCcCcccCCcCcccCc'
m2 = 'CCCCCccCccCcCCCCccCccccCccCccCCcCccCcCcCCcCccCccCc'
m3 = 'CccCCccCcCCCCCCCCCCcccCccCCCCCCccCCCcccCCCcCCcccCC'
m4 = 'cCCccCCccCCccCCccccCcCcCcCcCcCcCCCCccccCCCcCCcCCCC'
m5 = 'CCCcCcCcCcCCCcCCcCcCCccCcCCcccCccCCcCcCcCcCcccccCc'

In [9]:
type(m1)

str

In [13]:
#é necessário converter as strings para listas antes de criar o DF. Cada caracter vira um item da lista
eventos = {'m1': list(m1), 'm2': list(m2), 'm3': list(m3), 'm4': list(m4), 'm5': list(m5)}

In [14]:
eventos

{'m1': ['C',
  'C',
  'c',
  'C',
  'C',
  'c',
  'c',
  'C',
  'C',
  'C',
  'c',
  'c',
  'C',
  'c',
  'C',
  'c',
  'c',
  'C',
  'c',
  'C',
  'c',
  'C',
  'C',
  'C',
  'c',
  'C',
  'C',
  'c',
  'c',
  'c',
  'C',
  'C',
  'c',
  'C',
  'c',
  'C',
  'c',
  'C',
  'c',
  'c',
  'c',
  'C',
  'C',
  'c',
  'C',
  'c',
  'c',
  'c',
  'C',
  'c'],
 'm2': ['C',
  'C',
  'C',
  'C',
  'C',
  'c',
  'c',
  'C',
  'c',
  'c',
  'C',
  'c',
  'C',
  'C',
  'C',
  'C',
  'c',
  'c',
  'C',
  'c',
  'c',
  'c',
  'c',
  'C',
  'c',
  'c',
  'C',
  'c',
  'c',
  'C',
  'C',
  'c',
  'C',
  'c',
  'c',
  'C',
  'c',
  'C',
  'c',
  'C',
  'C',
  'c',
  'C',
  'c',
  'c',
  'C',
  'c',
  'c',
  'C',
  'c'],
 'm3': ['C',
  'c',
  'c',
  'C',
  'C',
  'c',
  'c',
  'C',
  'c',
  'C',
  'C',
  'C',
  'C',
  'C',
  'C',
  'C',
  'C',
  'C',
  'C',
  'c',
  'c',
  'c',
  'C',
  'c',
  'c',
  'C',
  'C',
  'C',
  'C',
  'C',
  'C',
  'c',
  'c',
  'C',
  'C',
  'C',
  'c',
  'c',
  'c',
  'C',
  'C',
  'C',
  'c',
  'C',
  'C',
  'c',
  'c',
  'c',
  'C',
  'C'],
 'm4': ['c',
  'C',
  'C',
  'c',
  'c',
  'C',
  'C',
  'c',
  'c',
  'C',
  'C',
  'c',
  'c',
  'C',
  'C',
  'c',
  'c',
  'c',
  'c',
  'C',
  'c',
  'C',
  'c',
  'C',
  'c',
  'C',
  'c',
  'C',
  'c',
  'C',
  'c',
  'C',
  'C',
  'C',
  'C',
  'c',
  'c',
  'c',
  'c',
  'C',
  'C',
  'C',
  'c',
  'C',
  'C',
  'c',
  'C',
  'C',
  'C',
  'C'],
 'm5': ['C',
  'C',
  'C',
  'c',
  'C',
  'c',
  'C',
  'c',
  'C',
  'c',
  'C',
  'C',
  'C',
  'c',
  'C',
  'C',
  'c',
  'C',
  'c',
  'C',
  'C',
  'c',
  'c',
  'C',
  'c',
  'C',
  'C',
  'c',
  'c',
  'c',
  'C',
  'c',
  'c',
  'C',
  'C',
  'c',
  'C',
  'c',
  'C',
  'c',
  'C',
  'c',
  'C',
  'c',
  'c',
  'c',
  'c',
  'c',
  'C',
  'c']}

In [15]:
moedas = pd.DataFrame(eventos)

In [16]:
moedas

   m1 m2 m3 m4 m5
0   C  C  C  c  C
1   C  C  c  C  C
2   c  C  c  C  C
3   C  C  C  c  c
4   C  C  C  c  C
5   c  c  c  C  c
6   c  c  c  C  C
7   C  C  C  c  c
8   C  c  c  c  C
9   C  c  C  C  c
10  c  C  C  C  C
11  c  c  C  c  C
12  C  C  C  c  C
13  c  C  C  C  c
14  C  C  C  C  C
15  c  C  C  c  C
16  c  c  C  c  c
17  C  c  C  c  C
18  c  C  C  c  c
19  C  c  c  C  C
20  c  c  c  c  C
21  C  c  c  C  c
22  C  c  C  c  c
23  C  C  c  C  C
24  c  c  c  c  c
25  C  c  C  C  C
26  C  C  C  c  C
27  c  c  C  C  c
28  c  c  C  c  c
29  c  C  C  C  c
30  C  C  C  c  C
31  C  c  c  C  c
32  c  C  c  C  c
33  C  c  C  C  C
34  c  c  C  C  C
35  C  C  C  c  c
36  c  c  c  c  C
37  C  C  c  c  c
38  c  c  c  c  C
39  c  C  C  C  c
40  c  C  C  C  C
41  C  c  C  C  c
42  C  C  c  c  C
43  c  c  C  C  c
44  C  c  C  C  c
45  c  C  c  c  c
46  c  c  c  C  c
47  c  c  c  C  c
48  C  C  C  C  C
49  c  c  C  C  c

In [17]:
#cria novo dataFrame 
df = pd.DataFrame(data =['Cara', 'Coroa'], index=['c', 'C'], columns=['Faces'])

In [18]:
df

   Faces
c   Cara
C  Coroa

In [23]:
moedas.count()

m1    50
m2    50
m3    50
m4    50
m5    50
dtype: int64

AttributeError: 'Series' object has no attribute 'values_count'